### ISSUE TITLE
ENH: Maximum produced/consumed reactive power

### ISSUE THREAD

**Issue by benoit9126** [RoseauTechnologies/Roseau_Load_Flow#126]
**Describe the feature you want. What problem does it solve?**
For flexible loads, the value `s_max` defines the maximum reactive power which can be consumed or produced for the Q(U) control. It would be great to define in this control two optional values to define the `q_min` and `q_max` to limit the maximum reactive power which can be consumed or produced.

Example:

```python
from roseau.load_flow import FlexibleParameter, Control, Projection, Q_

fp = FlexibleParameter(
    control_p=Control.constant(),
    control_q=Control.q_u(
        u_min=Q_(210, "V"), u_down=Q_(220, "V"), u_up=Q_(240, "V"), u_max=Q_(250, "V"),
        q_max=Q(2.5, "kVAr"), # <----- New value
        q_min=Q(-2, "kVAr"), # <----- New value
    ),
    projection=Projection(type="keep_p"),
    s_max=Q_(5, "kVA"),
)
```
In the Q(U) theoretical curve (see below), it will `q_max/s_max` would replace the "1" on the Y axis and `q_min/s_max` the "-1" on the Y axis. At any time, the value Q provided by the user must lie between `q_min` and `q_max`. Obviously, `abs(q_min)<s_max` and `abs(q_max)<s_max` and `q_min<q_max`

![](https://roseautechnologies.github.io/Roseau_Load_Flow/_images/Control_QU.svg)

@YassineAbdelouadoud

**Comment by YassineAbdelouadoud** [comment]
I would propose two additional specifications if possible : 

- Add the possibility to define `q_max` and `q_min` as percentage of `s_max`. This could be done by specifying the unit : `q_max=Q(2.5, "kVAr")`
- Add the possibility to set the reactive value inside the dead band (with a default value of 0)

**Comment by Saelyos** [comment]
@YassineAbdelouadoud 

Unfortunately specifying different units for `q_min` and `q_max` is a bit complicated, especially when the values are updated as `s_max`, `q_min` and `q_max` are linked together. I think it is better to leave it in the client code. 

Could you specify what you mean by 
> Add the possibility to set the reactive value inside the dead band (with a default value of 0)

Thanks.

**Comment by YassineAbdelouadoud** [comment]
By inside the dead band, I mean when the voltage is comprised between `u_down` and `u_up`. Adding the possibility to set the reactive power to a non-zero value would give another degree of freedom when configuring the Q(U) control.

**Comment by alihamdan** [comment]
> By inside the dead band, I mean when the voltage is comprised between `u_down` and `u_up`. Adding the possibility to set the reactive power to a non-zero value would give another degree of freedom when configuring the Q(U) control.

Q is not set to zero in this voltage range, it is set to the "theoretical reactive power" which you already have control over when you do `load = PowerLoad(id="ld", bus=bus, powers=Pth+1j*Qth, flexible_params=...)` (see the figure above). Is this the value you are asking for or did I not understand what you wanted?

**Comment by YassineAbdelouadoud** [comment]
My apologies, I missed the fact that this parameter was already available through the `PowerLoad` definition.
