### ISSUE TITLE
ENH: add line_type as an attribute of LineParameters when the .from_geometry constructor is used

### ISSUE THREAD

**Issue by YassineAbdelouadoud** [RoseauTechnologies/Roseau_Load_Flow#160]
**Describe the feature you want. What problem does it solve?**
Being able to retrieve the LineType class for a given Line. This could be an attribute of the Line instance or an attribute of its LineParameters. This would allow the user to easily identify the type of line.

**Describe alternatives you've considered**
Currently, I am using the first character of the LineParameters id

**Comment by benoit9126** [comment]
In the version 0.7.0-alpha, the `LineParameters`  constructor accepts the parameters `line_type`, `conductor_type` and `insulator_type`. Thus, the type of a line instance can be retrieved using `line.parameters.line_type`.

The full documentation of the API is available [here](https://www.roseau-load-flow.roseautechnologies.com/models/Line/index.html#api-reference).
