### ISSUE TITLE
DOC: Describe the proper way to replace a Transformer or a Line 

### ISSUE THREAD

**Issue by YassineAbdelouadoud** [RoseauTechnologies/Roseau_Load_Flow#162]
**Location of the document**
[disconnecting-an-element](https://roseautechnologies.github.io/Roseau_Load_Flow/usage/Connecting_Elements.html#disconnecting-an-element)

**Documentation problem**
The documentation explains how to disconnect a Load, but not the proper way to replace a Transformer or Line with a new one with different parameters. The use case would be : a constraint is violated in a transformer or line, the user wants to replace it with a larger one, without having to recreate the network from scratch.

**Comment by benoit9126** [comment]
The addendum is now available [here](https://www.roseau-load-flow.roseautechnologies.com/usage/Connecting_Elements.html#modifying-an-element). Be careful, the github.io pages still displays the doc of the 0.6.0 version. The new address for the documentation of v0.7.0 and following is https://roseau-load-flow.roseautechnologies.com.
