### ISSUE TITLE
Merging `to_dict` and `results_to_dict` methods

### ISSUE THREAD

**Issue by alihamdan** [RoseauTechnologies/Roseau_Load_Flow#176]
I am working on merging the `to_dict` and `results_to_dict` methods (also `..._to_json` methods) and I have a question about the new design.
The current in progress work adds a `include_results=True` parameter to these methods. This means that the results will be included by default when converting to a dict or to json. This however would fail if the results are invalid or if no load flow is run yet. Another option is to make the default `False` and error when the user set it to `True` when results are invalid. I see four options to move forward:

1. Include the results by default (`include_results=True`) and ignore them if they are invalid. Warn the user when trying to convert a network with invalid results.
2. Include the results by default (`include_results=True`) and ignore them if they are invalid silently (no warning).
3. Include the results by default (`include_results=True`) and raise an error when trying to convert a network with invalid results.
4. Do not include the results by default (`include_results=False`). Raise an error when trying to convert a network with explicit `include_results=True` passed by the user and invalid results.

I tend to prefer option 1. I think including the results is a good default and I don't like raising an error on freshly created networks with no load flow results.

What do you think would be the best option?

**Comment by benoit9126** [comment]
I would also include results by default, but I would like to make the difference between "invalid results" and "no results".

"Invalid results" exist when:
* a load flow has been triggered and raised an error
* an input has been modified without rerunning a load flow
In this case, `include_results=True` should raise an error. `include_results=False` should silently work. This category can be detected using `_results_valid` field of the `ElectricalNetwork` instance.

In case of "no results" (no load flow has been run on a fresh new network):
* `include_results=True` should work with a warning on the absence of results.
* `include_results=False` should silently work.
I think there is no way to detect this second situation. We may add a protected field named `_no_results: bool = True` which is set in the constructor of `ElectricalNetwork`. It is set to `False` when running a load flow, no matter the output of the load flow.

When importing an electrical network from a file, the fields `_no_results` and `_results_valid` should also be set according to the content of the file.
