### ISSUE TITLE
BUG: Bad transformer parameters can induce NaN values in the solver

### ISSUE THREAD

**Issue by Saelyos** [RoseauTechnologies/Roseau_Load_Flow#76]
**Describe the bug**
When bad parameters values are given to `TransformerParameters`, it can induce `NaN` values for `z2`, that will cause singular matrix. This is because of the line : 
``` python
l2_omega = np.sqrt((self._vsc * self._ulv**2 / self._sn) ** 2 - r2**2)
```

**To Reproduce**

```python
from roseau.load_flow import *

parameters = TransformerParameters(
    id="test",
    windings="Dyn11",
    sn=50000.0,
    uhv=20000.0,
    ulv=400.0,
    i0=0.027,
    p0=210.0,
    psc=2150.0,
    vsc=0.04,
)
print(parameters.to_zyk())
```

**Expected behavior**
An exception should be raised before running the load flow. 

**Version details**

Please copy/paste here the output of the function `show_versions`
```python
from roseau.load_flow import show_versions

show_versions()
```

```
# Paste here the output of the function `show_versions`

```

**Comment by Saelyos** [comment]
For magnetizing inductance, we prevent the negative sqrt by replacing it by 0 : 
```python
# Magnetizing inductance (Henry) * omega (rad/s)
if self._i0 * self._sn > self._p0:
    lm_omega = self._uhv**2 / (np.sqrt((self._i0 * self._sn) ** 2 - self._p0**2))
    ym = 1 / r_iron + 1 / (1j * lm_omega)
else:
    ym = 1 / r_iron
```

@alihamdan do you think we should do the same here or raise an error ?

**Comment by alihamdan** [comment]
I think it should be an error. It is physically impossible to have `Z = R+jX` where `|Z| < R`.

If you don't want to raise an error, I think we should at least warn the user when their P_{short-circuit} can lead to negative sqrt.

(I also think we should warn for the `lm_omega` case)
